name: MacOS Builds

on: workflow_dispatch

defaults:
  run:
    shell: bash
    
jobs:
  create_windows_builds:
    name: Create MacOS Builds
    runs-on: macos-latest

    steps:
    - name: Clone Godot
      uses: actions/checkout@v2
      with:
        repository: godotengine/godot
        ref: 3.2
        path: godot
    
    - name: Clone GLTF module
      uses: actions/checkout@v2
      with:
        repository: godot-extended-libraries/gltf
        path: godot/modules/gltf
    
    - name: Clone current repository
      uses: actions/checkout@v2
      with:
        repository: HungryProton/concept_graph_environment
        path: env

    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        architecture: 'x64'

    - name: Configuring Python packages
      run: |
        python -c "import sys; print(sys.version)"
        python -m pip install scons pywin32
        python --version
        scons --version
        
    - name: Compile Engine and Templates
      run: |
        cd godot
        scons -j2 platform=osx target=release_debug debug_symbols=no
        
        scons -j2 platform=osx tools=no target=release debug_symbols=no bits=64
        mv bin/godot.osx.opt.64 bin/template.osx.release
        
        scons -j2 platform=osx tools=no target=debug debug_symbols=no bits=64
        mv bin/godot.osx.debug.64 bin/template.osx.debug
    
    - name: Save binaries
      run: |
        rm -rf env/osx
        mkdir env/osx
        cp godot/bin/godot.osx.opt.tools.64 env/osx
        cp godot/bin/template.osx.release env/osx
        cp godot/bin/template.osx.debug env/osx
    
    - name: Commit and Push
      uses: EndBug/add-and-commit@v4
      with:
        add: osx
        cwd: env
        message: MacOS builds from Github Actions
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
